### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by JohnDoe56248** [cornertime/cornertime#3] opened 2020-10-19 00:51 UTC
Hello,

I don't hear any audio. Not when the cornertime session starts, when extra minutes is added or when the time is over.
All the other stuff is working fine. I see the countdown and I see that there get more minutes added after I keep giving movements in the webcam.
I tried in chrome 86.0.4240.75, firefox 81.0.2 and edge 86.0.622.43. I used to hear the audio I am almost sure of. But that was a long time ago.

Thanks in advanced
And thanks for making this app!
Greetings

**Comment by japsu** [comment] 2020-10-19 09:04
Thanks for the report. Which OS are you on?

Can't reproduce on Chrome 86.0.4240.80, macOS 10.15.7.

If you open the Console under Developer tools (menu > More Tools), are there any error messages?

**Comment by JohnDoe56248** [comment] 2020-10-19 17:24
Thanks for the quick response!

I use it with Windows 10.
I already checked the console in chrome dev tools. I open the console in dev tools, then refresh the page and i don't see any console message.

I looked up the code a bit and found that you are using 'speechSynthesis'. I found that there are more people who have problems with it since chrome updates here: https://support.google.com/chrome/thread/22877008?hl=en

I found a jsfiddle where the speechSynthesis works on my browser: https://jsfiddle.net/notthetup/rwx1yxem/

I'm not sure if there is something wrong on my side, but this is what I found and maybe you can do/see something with this info.

Thanks in advance again!
Greetings

**Comment by japsu** [comment] 2020-10-22 16:15
Also unable to reproduce on Chrome 86.0.4240.75, Windows 10 version 20H2 19042.572 - speech synthesis works just fine.

I wonder if this has something to do with installed Windows components? After all, I think the browsers delegate to the operating system instead of rolling their own.

**Comment by japsu** [comment] 2020-10-31 08:02
Closing due to being unable to reproduce. If you have any further findings related to the conditions under which this problem might manifest itself, please reopen.

**Closed by japsu** 2020-10-31 08:02 UTC

**Comment by framingnoone** [comment] 2021-03-30 00:04
I had this problem also, but it went away after a few refreshes. Maybe some weird combo of not loading everything the first time through, or something. No other immediately obvious problems with the webapp version.
